<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Copy your short link' => 'Скопируйте Вашу короткую ссылку',
    'Developed by' => 'Разработано',
    'Enter your link to the field below.' => 'Введите Вашу ссылку в поле ниже.',
    'Link' => 'Ссылка',
    'Short Link' => 'Короткая ссылка',
    'Shorten' => 'Укоротить',
    'Something went wrong. Please, check the link above or try again later.' => 'Что-то пошло не так. Пожалуйста, проверьте ссылку выше или попробуйте еще раз позже.',
    'The requested page not found.' => 'Запрашиваемая страница не найдена.',
    'URL shortener service.' => 'Сервис укорачивания URL.',
];
